### ISSUE TITLE
Add manual simulation mode for electoral map

### ISSUE THREAD

**Issue by rabbah** [nimbella/demo-projects#23]
Allow page visitor to click on sate to assign the electoral votes to one of the two parties and tally up the results. This permits the user to simulate a path to victory.

**Comment by bhageena** [comment]
This is in place, one needs to click either `Select Blue States`  or `Select Red States`, after clicking the button becomes `Selected`. Following click on any state in the map colors the state in the selected color and the numbers are adjusted accordingly.
