### ISSUE TITLE
Add Jest unit tests for API functions

### ISSUE THREAD

**Issue by rabbah** [nimbella/demo-projects#24]
There are several APIs implemented as serverless functions located in the `election/packages` directory:
https://github.com/nimbella/demo-projects/tree/master/election/packages/ge2020

Some of these functions make API calls to the Google civic API. Add unit tests for each API/function by mocking the API call and simulating the API response. 
- [x] [Voter Info](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/voterinfo/index.js)
- [x] [Representatives](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/reps/index.js)
- [x] [Election Data](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/elections/index.js)
- [x] [Divisions](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/divisions/index.js)

**Comment by MohanreddyMummareddy** [comment]
I need some inputs for this. I don't know exactly how to proceed with the initialization of Jest with the current project. I know it's done by React.js but still, i'm not sure how to install the Jest and write the test API for the specified functions.

**Comment by rabbah** [comment]
Thanks for the interest! I’ll add more details.

**Comment by bhageena** [comment]
Unit tests have been included via PR #50
