### ISSUE TITLE
Move initializer to init time

### ISSUE THREAD

**Issue by rabbah** [nimbella/demo-projects#25]
Several of the API functions read files into memory but do so inside `main()`. Instead move these to init time and remove the conditional check.

For example, `exitpolls`
https://github.com/nimbella/demo-projects/blob/b3fe3ae162205683f054cd2562faf700606cf8c3/election/packages/ge2020/exitpolls/index.js#L3-L10

becomes:
```
const contents = fs.readFileSync(__dirname + '/exitpolls.json', 'UTF-8');
const body = JSON.parse(contents)

function main(args) {
	return { body }
}
```

There are several functions like this:
- [x] [Resources](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/resources/index.js)
- [x] [Time Series](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/timeseries/index.js)
- [x] [State/Counties](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/state_counties/index.js)
- [x] [Exit Polls](https://github.com/nimbella/demo-projects/blob/master/election/packages/ge2020/exitpolls/index.js)

**Comment by bhageena** [comment]
Suggestions have been incorporated in all mentioned files.
