### ISSUE TITLE
election app loads invalid urls 

### ISSUE THREAD

**Issue by rabbah** [nimbella/demo-projects#33]
When you first load the `divisions` and `voter info` pages there's is an invalid page load.

<img width="985" alt="Screen Shot 2020-10-09 at 10 50 57 AM" src="https://user-images.githubusercontent.com/4959922/95600431-363b0180-0a20-11eb-884d-8fcb5cdb5203.png">
<img width="971" alt="Screen Shot 2020-10-09 at 10 51 56 AM" src="https://user-images.githubusercontent.com/4959922/95600469-3935f200-0a20-11eb-951a-83882e3bb220.png">

**Comment by bhageena** [comment]
This has been taken care of via the linked PR. We are now using HashRouter.
