### ISSUE TITLE
election API docs should clarify what base url means

### ISSUE THREAD

**Issue by rabbah** [nimbella/demo-projects#35]
When navigating through the election starter APIs, there's a `baseURL` place holder but it's unclear what this value should be. It's not the domain name for the project deployment but the domain name + `/api/ge2020/`.

<img width="475" alt="Screen Shot 2020-10-09 at 11 15 32 AM" src="https://user-images.githubusercontent.com/4959922/95600894-c11bfc00-0a20-11eb-93ee-1f4ad68e818d.png">

**Comment by bhageena** [comment]
This has been taken care of via the linked PR.
