### ISSUE TITLE
Election demo web build started breaking due to dependency change

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [nimbella/demo-projects#47]
The election demo has a lot of open dependencies.   It recently entered a state where the actual dependencies that are loaded are inconsistent:

```
> election@1.0.0 build .../main/config/deployable/election/web
> react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/mobx-react-lite/es/utils/assertEnvironment.js
Attempted import error: 'makeObservable' is not exported from 'mobx'.
```

This breaks the Jenkins deploy job.   I am separately recommending that we take the election demo out of the main build until this is fixed.

**Comment by joshuaauerbachwatson** [comment]
The election demo is (temporarily, at least) removed from dev builds to keep the Jenkins pipeline running.

If the demo is fixed, the change in `main` is easily reversed.   If, for some reason we can't (or decide not to) fix the demo build, then it should probably be retired completely because I believe customers would have problems building it as well.

**Comment by joshuaauerbachwatson** [comment]
The PR to fix this has been verified and merged.   We can wait to close the issue until after we verify the build again as part of the main Nimbella build.

**Comment by rabbah** [comment]
I suggest setting up GitHub actions to build the demos.

**Comment by bhageena** [comment]
The issue has been resolved, and the actionable item herein has been moved out as an independent issue.
